---
- name: set config directiory
  lineinfile: 
    dest: /usr/local/nagios/etc/nagios.cfg 
    regexp: "cfg_dir=/usr/local/nagios/etc/servers" 
    line: "cfg_dir=/usr/local/nagios/etc/servers" 
    state: present
  tags:
    - set_config

- name: check if server config directiory exists
  command: bash -c "ls /usr/local/nagios/etc/ | grep servers"
  register: dir_exists
  ignore_errors: true
  tags:
    - create_config_dir

- name: create server config directiory
  file: path=/usr/local/nagios/etc/servers state=directory
  when: dir_exists|failed
  tags:
    - create_config_dir

- name: set email address
  lineinfile:
    dest: /usr/local/nagios/etc/objects/contacts.cfg
    regexp: "email" 
    line: "email {{ email }}" 
    state: present
  tags:
    - set_email

- name: check if email is set
  command: bash -c "cat /usr/local/nagios/etc/objects/contacts.cfg | grep email"
  register: email_set

- name: add check_nrpe command
  blockinfile:
    dest: /usr/local/nagios/etc/objects/commands.cfg
    block: |
      define command{
        command_name check_nrpe
        command_line $USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$
      }
  tags: 
    - add_check_nrpe

- name: configure apache authentication
  command: bash -c "a2enmod rewrite; a2enmod cgi"

- name: Check if python passlib is installed
  command: bash -c "dpkg --get-selections | grep python-passlib"
  register: passlib_installed
  ignore_errors: True
  tags:
    - passlib_setup

- name: Install python passlib
  apt: name=python-passlib state=present force=yes
  when: passlib_installed|failed
  tags:
    - passlib_setup

- name: create nagios user and password
  htpasswd: path=/usr/local/nagios/etc/htpasswd.users name=nagiosadmin password={{ nagios_password }}
  tags:
    - password

- name: create symlink for nagios.conf and start nagios on boot
  file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
  with_items:
    - { src: '/etc/apache2/sites-available/nagios.conf', dest: '/etc/apache2/sites-enabled/nagios.conf' }
    - { src: '/etc/init.d/nagios', dest: '/etc/rcS.d/S99nagios' }
  tags:
    - symlink 

- name: start nagios
  service: name={{ item }} state=restarted
  with_items:
    - nagios
    - apache2

